### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ellingsoc** [paulmandal/atak-forwarder#115]
Running atak 4.5.1.4  with the latest forwarder and atak instantly crashes when you click on Atak forwarder preferences. Running a pixel 5 with android 12

**Comment by Ellingsoc** [comment]
I have no idea how to pull one of create one. Is there a guide on how to do
so? I'd be happy to try to get it for you.

**Comment by paulmandal** [comment]
The easiest way is to install Android Studio: https://developer.android.com/studio
Then enable Developer Mode on your device: https://developer.android.com/studio/debug/dev-options

Connect your phone to your computer and click Yes or OK when it asks whether to allow USB Debugging, then in Android Studio in the Logcat tab (at the bottom of the screen) there is a dropdown for log level (it will say Verbose as the default) click Error and then open ATAK and reproduce the crash. You should see a message like 

```
java.lang.Exception: Stack trace
at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
at com.ericgoebelbecker.stacktraces.StackTrace.d(StackTrace.java:23)
at com.ericgoebelbecker.stacktraces.StackTrace.c(StackTrace.java:19)
at com.ericgoebelbecker.stacktraces.StackTrace.b(StackTrace.java:15)
at com.ericgoebelbecker.stacktraces.StackTrace.a(StackTrace.java:11)
at com.ericgoebelbecker.stacktraces.StackTrace.main(StackTrace.java:7)```

That is the stack trace for the crash and will tell me where the crash originated.

**Comment by Ellingsoc** [comment]
Heres more of the read out. I dont see anything that says stack trace.

2022-02-12 13:52:23.332 1670-1670/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.atakmap.app.civ, PID: 1670
    java.lang.NullPointerException: Attempt to invoke virtual method
'boolean java.lang.String.startsWith(java.lang.String)' on a null object
reference
        at atakplugin.PluginTemplate.t5.a(SourceFile:5)
        at atakplugin.PluginTemplate.u5.<init>(SourceFile:3)
        at atakplugin.PluginTemplate.Y4.onCreate(SourceFile:5)
        at android.app.Fragment.performCreate(Fragment.java:2486)
        at
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
        at
android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at
android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at
android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at
android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-02-12 13:52:23.428 1670-1693/? E/SharedPreferencesImpl: Couldn't
create directory for SharedPreferences file
/data/user/0/com.paulmandal.atak.forwarder/shared_prefs/com.paulmandal.atak.forwarder_preferences.xml
2022-02-12 13:52:23.970 954-960/? E/statsd: DurationMetric
2271129699865384196 dropping data for what dimension key
(10)0x2010101->10190[I] (10)0x30000->CastSocketMultiplexer_WakeLock[S]
2022-02-12 13:52:23.970 954-960/? E/statsd: DurationMetric
1897601926725174045 dropping data for what dimension key
(10)0x2010101->10190[I] (10)0x30000->CastSocketMultiplexer_WakeLock[S]
2022-02-12 13:52:24.191 954-960/? E/statsd: DurationMetric
2271129699865384196 dropping data for what dimension key
(10)0x2010101->10190[I] (10)0x30000->CastSocketMultiplexer_WakeLock[S]
2022-02-12 13:52:24.191 954-960/? E/statsd: DurationMetric
1897601926725174045 dropping data for what dimension key
(10)0x2010101->10190[I] (10)0x30000->CastSocketMultiplexer_WakeLock[S]
2022-02-12 13:52:24.192 954-960/? E/statsd: DurationMetric
2271129699865384196 dropping data for what dimension key
(10)0x2010101->10190[I]
(10)0x30000->CastDeviceController-com.google.android.gms[S]
2022-02-12 13:52:24.192 954-960/? E/statsd: DurationMetric
1897601926725174045 dropping data for what dimension key
(10)0x2010101->10190[I]
(10)0x30000->CastDeviceController-com.google.android.gms[S]
2022-02-12 13:52:26.663 1670-1670/? E/ACRA: ACRA caught a
NullPointerException for com.atakmap.app.civ
    java.lang.NullPointerException: Attempt to invoke virtual method
'boolean java.lang.String.startsWith(java.lang.String)' on a null object
reference
        at atakplugin.PluginTemplate.t5.a(SourceFile:5)
        at atakplugin.PluginTemplate.u5.<init>(SourceFile:3)
        at atakplugin.PluginTemplate.Y4.onCreate(SourceFile:5)
        at android.app.Fragment.performCreate(Fragment.java:2486)
        at
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
        at
android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at
android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at
android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at
android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-02-12 13:52:26.705 567-567/? E/SELinux: avc:  denied  { find } for
pid=2205 uid=10386 name=meminfo
scontext=u:r:untrusted_app:s0:c130,c257,c512,c768
tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
2022-02-12 13:52:26.713 1670-1670/? E/ACRA: Not adding buildConfig to log.
Class Not found : com.atakmap.app.BuildConfig. Please configure
'buildConfigClass' in your ACRA config
2022-02-12 13:52:26.823 1670-2228/? E/ACRA: Unknown json subtree type, see
issue #186
2022-02-12 13:52:27.040 1727-3178/? E/WifiMulticastLockManager: Multicaster
binderDied
2022-02-12 13:52:27.065 621-621/? E/BpTransactionCompletedListener: Failed
to transact (-32)
2022-02-12 13:52:27.066 978-1884/? E/LocSvc_ApiV02: reportLocEvent:3908]
Loc event report: 0 KlobucharIonoMode_valid:0: leapSec_valid:1:
tauC_valid:1 featureStatusReport_valid: 0 featureStatusReport: 0
2022-02-12 13:52:27.109 2344-3129/? E/bt_stack:
[ERROR:bta_gattc_utils.cc(441)] bta_gattc_mark_bg_conn unable to find the
bg connection mask for bd_addr=30:c6:f7:1e:8c:c2

**Comment by Ellingsoc** [comment]
Happy to report that its working great man. Awesome job man!

**Comment by paulmandal** [comment]
Great to hear! Thank you for reporting the issue and for giving me the stack trace I needed to get it fixed.
