### ISSUE TITLE
ATAK crashing once plugin activated

### ISSUE THREAD

**Issue by lonewaffle** [paulmandal/atak-forwarder#161]
I have several devices:
1x Samsung Galaxy S9+
2x Samsung Galaxy S7
3x Motorola G8

I've tested ATAK 4.6.1 and 4.7.0.1 and Meshtastic 2.0.1 - 2.0.20

The 3 Motorolas and S9+ work great on ATAK 4.7.0.1 with forwarder 2.0.2 and 2.0.3. The S7 devices crash on both versions of ATAK when using forwarder 2.0.2 or 2.0.3.

Here's the error I'm seeing in Android Studio:

com.atakmap.app.civ                  E  ACRA caught a NullPointerException for com.atakmap.app.civ
										java.lang.NullPointerException: Attempt to read from field 'boolean androidx.lifecycle.LiveData.mDispatchingValue' on a null object reference
											at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:138)
											at atakplugin.AtakForwarder.gr.a(SourceFile:63)
											at atakplugin.AtakForwarder.gi.a(SourceFile:83)
											at atakplugin.AtakForwarder.gi.lambda$RUSKg0TKdjCYVNFPUG3K1cAjdS4(Unknown Source:0)
											at atakplugin.AtakForwarder.-$$Lambda$gi$RUSKg0TKdjCYVNFPUG3K1cAjdS4.run(Unknown Source:8)
											at android.os.Handler.handleCallback(Handler.java:789)
											at android.os.Handler.dispatchMessage(Handler.java:98)
											at android.os.Looper.loop(Looper.java:164)
											at android.app.ActivityThread.main(ActivityThread.java:6944)
											at java.lang.reflect.Method.invoke(Native Method)
											at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
											at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

I don't know if it matters, but the S7 devices are running Android 8.0.0

Please let me know if there's anything I can do to provide more useful information.

Thanks for all that you do.

**Comment by paulmandal** [comment]
Thank you for this info, especially the stack trace, I'll try to determine the cause and get a patch into the next release.
