### ISSUE TITLE
Forwarder Lifecycle failed to load?

### ISSUE THREAD

**Issue by MrWinemaker** [paulmandal/atak-forwarder#199]
Got weird error

ATAK Forwarder component: com.paulmandal.atak.forwarder.plugin.ForwarderLifecycle is not compatible or failed to load properly

I am attempting to run it on an Amazon Fire 8, which reddit says is the issue but figure id see here?  Error happens on every compatible version of ATAK + Forwarder

**Comment by paulmandal** [comment]
Do you have a stack trace from ATAK or logcat for when this happens? The Fire 8 device may be missing something the Forwarder plugin expects to use.

**Comment by MrWinemaker** [comment]
Alrighty I just tried to reinstall the plugin in ATAK while plugged into my PC, logcat gave me this error (I apologize in advance, I don't know GirHub comment etiquite so I'm not sure if I should just be posting a big lump of error message here.  Very new to this)

error with plugin com.paulmandal.atak.forwarder (please uninstall): com.paulmandal.atak.forwarder.plugin.ForwarderLifecycle
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/atakmap/android/maps/ab;
	at com.paulmandal.atak.forwarder.plugin.ForwarderLifecycle.onPause(SourceFile:1)
	at com.atak.plugins.impl.LifecycleMapComponent.onPause(SourceFile:197)
	at com.atakmap.android.maps.MapActivity.unregisterMapComponent(SourceFile:303)
	at com.atak.plugins.impl.AtakPluginRegistry.unloadPlugin(SourceFile:1280)
	at com.atak.plugins.impl.LifecycleMapComponent.reportError(SourceFile:56)
	at com.atak.plugins.impl.LifecycleMapComponent.reportError(SourceFile:45)
	at com.atak.plugins.impl.LifecycleMapComponent.access$400(SourceFile:33)
	at com.atak.plugins.impl.LifecycleMapComponent$2.run(SourceFile:153)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6775)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.atakmap.android.maps.ab" on path: DexPathList[[zip file "/data/app/com.paulmandal.atak.forwarder-id5u4P9w4GB_Az7BhvF5sA==/base.apk"],nativeLibraryDirectories=[/data/app/com.paulmandal.atak.forwarder-id5u4P9w4GB_Az7BhvF5sA==/lib/arm, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.paulmandal.atak.forwarder.plugin.ForwarderLifecycle.onPause(SourceFile:1) 
	at com.atak.plugins.impl.LifecycleMapComponent.onPause(SourceFile:197) 
	at com.atakmap.android.maps.MapActivity.unregisterMapComponent(SourceFile:303) 
	at com.atak.plugins.impl.AtakPluginRegistry.unloadPlugin(SourceFile:1280) 
	at com.atak.plugins.impl.LifecycleMapComponent.reportError(SourceFile:56) 
	at com.atak.plugins.impl.LifecycleMapComponent.reportError(SourceFile:45) 
	at com.atak.plugins.impl.LifecycleMapComponent.access$400(SourceFile:33) 
	at com.atak.plugins.impl.LifecycleMapComponent$2.run(SourceFile:153) 
	at android.os.Handler.handleCallback(Handler.java:873) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loop(Looper.java:211) 
	at android.app.ActivityThread.main(ActivityThread.java:6775) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by MrWinemaker** [comment]
> Do you have a stack trace from ATAK or logcat for when this happens? The Fire 8 device may be missing something the Forwarder plugin expects to use.

Actually what it might be, the Amazon Fire does not have GPS.  I was trying to use my mesh device and forwarder to use that as it's GPS.  Would that be why forwarder lifecycle is returning errors?
